<script>
	import { navigate } from "svelte-routing";
	import { fly } from 'svelte/transition';

	import Button from '../components/Button.svelte';
	import DevInfo from './DevInfo.svelte';

	import { showAlert } from '../lib/ui/helpers';

	let showTutorial = false;

	async function scan() {
		if (navigator.onLine === false) {
            await showAlert(
                'Error', 
                'You need Internet connectivity to verify a Device Credential' 
            );
            return;
        }
	    // We ensure that only the Camera is switched on when we want
	    window['cameraStatus'] = 'on';
        navigate('scan');
    }

	function onClickDev() {
		showTutorial = true;
	}

	function goBack() {
        navigate('home');
    }
</script>

<style>
	main {
		height: 100%;
        background: #F8F8F8;
        flex-direction: column;
        display: flex;
        flex: 1;
	}

	header {
			display: flex;
			flex-direction: column;
			height: 72px;
			background: linear-gradient(90deg, #00FFFF 0%, #0099FF 100%);
	}

	section > p {
        font-family: 'Proxima Nova', sans-serif;
        font-style: normal;
        font-weight: 400;
        font-size: 2.08vh;
        line-height: 3.3vh;
        color: #6f7a8d;
        text-align: center;
        padding: 0px 3vw;
		margin-top: 1.75vh ;
    }
	
	.options-wrapper > p {
		font-family: 'Proxima Nova', sans-serif;
		font-weight: 600;
		font-size: 2.3vh;
        line-height: 2.7vh;
		color: #F8F8F8;
		margin: 0;
		z-index: 1;
	}

	.options-wrapper {
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
		margin: 3.5vh;
    }

	.box-wrapper {
		background: white;
		padding: 1.75vh;
		display: flex;
		align-items: center;
		height: 7.9vh;
		margin: 0 3.6vh;
	}

	.box-wrapper > img {
		margin-right: 1.75vh;
	}

	.box-wrapper > p {
		font-family: 'Proxima Nova', sans-serif;
		font-weight: 600;
		font-size: 2vh;
		line-height: 2.6vh;
		color: #8593AC;
	}

	img {
		margin: 0 !important;
	}

	.scan {
		padding-right: 1.3vh;
	}

	.code {
		margin-left: auto;
	}

	.subheader > p {
        font-family: 'Proxima Nova', sans-serif;
        font-weight: 700;
        font-size: 2.6vh;
        line-height: 3.2vh;
        margin: 6.5vh 3.6vh 17.5vh 3.6vh !important;
        white-space: pre-line;
        text-align: center;
        color: #051923;
    }

	footer {
        width: 100%;
        position: absolute;
        bottom: 0;
    }
</style>

<main transition:fly="{{ x: 500, duration: 500 }}">
	{#if showTutorial}
		<DevInfo page="Presentation" bind:showTutorial={showTutorial} />
	{/if}

	{#if !showTutorial}
		<header>
			<div class="options-wrapper">
				<img src="../assets/chevron-left.svg" on:click="{goBack}" alt="back" />
				<p>Request Device DID credential</p>
				<img class="code" src="../assets/code.svg" on:click="{onClickDev}" alt="code" />
			</div>
		</header>

		<div class="subheader">
			<p>Receive Device DID credential</p>
		</div>

		<section>
			<div class="box-wrapper">
				<img src="../assets/device-small.png" alt="device" />
				<p>Device DID</p>
			</div>
			<p>Scan the Data Matrix code generated by the Issuer app</p>
		</section>

		<footer>
			<Button style="background: #00A7FF; color: white; height: 64px;" 
					label="Scan code"
					onClick="{scan}">
				<img class="scan" src="../assets/scan.png" alt="scan" />
			</Button>
		</footer>
	{/if}
</main>