name: Common package

on:
  push:
    branches:
      - main
      - dev
    paths: 
      - 'packages/common/**'
  pull_request:
    branches:
      - main
      - dev
    paths: 
      - 'packages/common/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Update NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run build:lint -w packages/common

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Update NPM
        run: npm install -g npm
      - name: Run Jest
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:ci -w packages/common

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Update NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -w packages/common
      - name: Upload public directory
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: packages/common/dist
