name: Build & Test Holder Svelte App

on:
  push:
    branches:
      - main
      - dev
    paths: 
      - 'identity-enabler/holder-mobile-app/**'
      - '!identity-enabler/holder-mobile-app/android/**'
  pull_request:
    branches:
      - main
      - dev
    paths: 
      - 'identity-enabler/holder-mobile-app/**'
      - '!identity-enabler/holder-mobile-app/android/**'

defaults:
  run:
    working-directory: identity-enabler/holder-mobile-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: identity-enabler/holder-mobile-app/package-lock.json
      - name: Update NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run build:lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: identity-enabler/holder-mobile-app/package-lock.json
      - name: Update NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
