name: 'Test Report'
on:
  workflow_run:
    workflows:
      - Device ID Svelte app
      - Holder Svelte app
      - Verifier Svelte app
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JEST Tests
          path: '*.xml'
          reporter: jest-junit