name: Verifier Svelte app

on:
  push:
    branches:
      - main
      - dev
    paths: 
      - 'identity-enabler/verifier-mobile-app/**'
      - '!identity-enabler/verifier-mobile-app/android/**'
  pull_request:
    branches:
      - main
      - dev
    paths: 
      - 'identity-enabler/verifier-mobile-app/**'
      - '!identity-enabler/verifier-mobile-app/android/**'

defaults:
  run:
    working-directory: identity-enabler/verifier-mobile-app

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: identity-enabler/verifier-mobile-app/package-lock.json
      - name: Update NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run build:lint
      - name: Run Jest
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: identity-enabler/verifier-mobile-app/package-lock.json
      - name: Update NPM
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload built app
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: identity-enabler/verifier-mobile-app/public
